import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./SideBar/SideBar";
import Navbar from "./NavBar/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={styles.container}>
        <Sidebar/>
        <div style={styles.content}>
        <Navbar />
        </div>
        </div>
        {children}
      </body>
    </html>
  );
}

const styles = {
  container: {
    display: 'flex',
  },
  content: {
    marginLeft: '250px',
    flex: 1,
  },
  main: {
    padding: '20px',
  }
};